// Auto-generated by batch/fetch-prs.ts
// Last updated: 2025-12-22 02:16:44

import type { Organization } from "@/lib/types";

export const orgs: Organization[] = [
  {
    "name": "Love-Rox",
    "avatarUrl": "https://github.com/Love-Rox.png",
    "prCount": 92
  },
  {
    "name": "sasagar",
    "avatarUrl": "https://github.com/sasagar.png",
    "prCount": 39
  },
  {
    "name": "misskey-dev",
    "avatarUrl": "https://github.com/misskey-dev.png",
    "prCount": 4
  },
  {
    "name": "automuteus",
    "avatarUrl": "https://github.com/automuteus.png",
    "prCount": 3
  },
  {
    "name": "tkgstrator",
    "avatarUrl": "https://github.com/tkgstrator.png",
    "prCount": 3
  },
  {
    "name": "wp-cli",
    "avatarUrl": "https://github.com/wp-cli.png",
    "prCount": 2
  },
  {
    "name": "couetilc",
    "avatarUrl": "https://github.com/couetilc.png",
    "prCount": 1
  },
  {
    "name": "gethomepage",
    "avatarUrl": "https://github.com/gethomepage.png",
    "prCount": 1
  },
  {
    "name": "exeldro",
    "avatarUrl": "https://github.com/exeldro.png",
    "prCount": 1
  },
  {
    "name": "wordcamposaka2019",
    "avatarUrl": "https://github.com/wordcamposaka2019.png",
    "prCount": 1
  },
  {
    "name": "lvgamedev",
    "avatarUrl": "https://github.com/lvgamedev.png",
    "prCount": 1
  },
  {
    "name": "woocommerce",
    "avatarUrl": "https://github.com/woocommerce.png",
    "prCount": 1
  },
  {
    "name": "mokumoku-temple",
    "avatarUrl": "https://github.com/mokumoku-temple.png",
    "prCount": 1
  },
  {
    "name": "wcosaka2018",
    "avatarUrl": "https://github.com/wcosaka2018.png",
    "prCount": 1
  }
];
