// Auto-generated by batch/fetch-prs.ts
// This is a placeholder. Run `npm run batch:prs` to fetch real data.

import type { Organization } from "@/lib/types";

export const orgs: Organization[] = [
  {
    name: "vercel",
    avatarUrl: "https://github.com/vercel.png",
    prCount: 1,
  },
  {
    name: "facebook",
    avatarUrl: "https://github.com/facebook.png",
    prCount: 1,
  },
  {
    name: "tailwindlabs",
    avatarUrl: "https://github.com/tailwindlabs.png",
    prCount: 1,
  },
  {
    name: "microsoft",
    avatarUrl: "https://github.com/microsoft.png",
    prCount: 1,
  },
  {
    name: "shadcn-ui",
    avatarUrl: "https://github.com/shadcn-ui.png",
    prCount: 1,
  },
];
